### PR TITLE
API Implement cache / move to silverstripe vendor

### PR DESCRIPTION
**Pull request by tractorcow**
See https://github.com/silverstripe/silverstripe-assets/issues/43 for parent story

Still need to write unit tests, but this can be peer reviewed in the mean time

### CODE REVIEW

**Comment by sminnee** [comment]
What's the best way to set up an integration test rig for this? Does it just need an S3 bucket?

**Comment by tractorcow** [comment]
I was thinking about using a mock for the s3 client, actually.

**Comment by sminnee** [comment]
Yeah then it wouldn't be an integration test, it'd be a component test.

With a vanilla S3 bucket, would it be feasible to do an integration test of this with the substantial caveat that protected assets were publicly accessible?

**Comment by tractorcow** [comment]
In order to test this out:

 - Setup your s3 bucket as per readme.md
 
 ```
 
 - Set your `.env` with:
 
 ```
AWS_REGION="ap-southeast-2"
AWS_BUCKET_NAME="silverstripe-solutions-ss4test"
AWS_ACCESS_KEY_ID="<redacted>"
AWS_SECRET_ACCESS_KEY="<redacted>"
```

**Comment by sminnee** [comment]
Edge-case issue: if you don't have write permission on the bucket, the error isn't helpful https://gist.github.com/sminnee/24f5831a0aa87c18b12d5918ea04aad6 - it would be better if it said "The webserver doesn't have permission to write the file to S3" or something in the response.

**Comment by sminnee** [comment]
OK — I've got this working but there's a bug. Draft assets are using the *public* asset URLs for their thumbnails, which don't yet exist and so throw "forbidden" errors.

**Comment by tractorcow** [comment]
Yes, something broken recently. Looking at this bug now.

**Comment by tractorcow** [comment]
I've traced this to a bug where exists() would use getMetadata(), and rely on potentially cached data which never actually calls the backend. We need a concept for agnostic-exists (will invoke a cache miss).

**Comment by tractorcow** [comment]
Updated with tests @sminnee 

The public url bug is fixed.

**Comment by tractorcow** [comment]
Tests green. :P

**Comment by sminnee** [comment]
I've done a local test and it works for me now and the code looks pretty good.

**Pull request merged**
