### PR TITLE
feat: implement CacheItemsTrait for better performance handling

### PR DESCRIPTION
**Pull request by wilr**
As reported by https://github.com/silverstripe/silverstripe-s3/issues/67, https://github.com/silverstripe/silverstripe-s3/issues/48 and others the performance of this module on flysystem 3 is bad, very bad. This is my attempt at overhauling the performance of the module to get better results out of the box. 

In the original upgrade we picked up `jgivoni/flysystem-cache-adapter` thinking it would go a job but actually caused more headaches - turned out easier to implement something tailored to our needs.

The new CacheItems integrations natively with the existing CacheInterface within Silverstripe so works out of the box but can also be used with memcached, redis etc. 

Performance wise, warm cache it makes 0 calls to AWS. On a cold cache it makes 3N calls for published files (doesObjectExistV2, readObject, fetchFileMetadata).

### CODE REVIEW

**Comment by wilr** [comment]
Note for anyone testing, there are several YAML changes. The intention was this release we'll make a new major version rather than a minor.

**Comment by obj63mc** [comment]
Will test this in the morning but at first glance, using a new Asset Store looks like it will have the biggest performance gains and essentially is what I have implemented custom already on most of my sites. 

Also for sites that have a ton of files or a lot of users, this issue is causing some problems as well https://github.com/silverstripe/silverstripe-framework/issues/11272

Last thing I noticed in some of the other silverstripe repos are pull requests to not use self:: for calling a class' static method. https://github.com/silverstripe/silverstripe-cms/pull/2955 
I saw a few instances of that in the new files so that might want to be checked.

**Comment by obj63mc** [comment]
Testing currently on one of our larger sites, with over 20k users, 17k files, 22k pages.  Overall seems to be working great.  Initial load in asset admin still a bit slow but don't know if there will ever be anything that can be done for that when trying to load metadata for 25+ files at once.  Will monitor for the next day or so and let you know if I see any issues

**Comment by obj63mc** [comment]
One thing that I am not 100% sure if this is configurable or not is if there is a way to disable the flushable portion of this cache.  Main reason why is I am using Redis to store the cache, but hosting on heroku - when they restart the server daily or we deploy a code change, this cache is then flushed even though we don't need it to.

@wilr - do you know if there is a way to disable that.  I think that would be a huge help for people on hosting platforms like heroku

**Comment by obj63mc** [comment]
Okay, so I have added in some small code to allow the cache flushing to be configurable in the same manner that SilverStripe\Assets\InterventionBackend allows for this.

One issue that I am having though is when trying to utilize the PublicCDNAdapter by setting the .env variable of AWS_PUBLIC_CDN_PREFIX - The public url returned is always the s3 bucket url and not the CDN url.  I can also see stored in the cache the public url being stored with out the cdn prefix.

At line https://github.com/silverstripe/silverstripe-s3/blob/pr/performance/src/Adapter/CachedAwsS3V3Adapter.php#L97
Since this is calling parent::publicURL we are then calling the AwsS3V3Adapter public url method where we really want to be getting the PublicAdapter's or PublicCDNAdapter's getPublicUrl method - 

https://github.com/silverstripe/silverstripe-s3/blob/pr/performance/src/Adapter/PublicAdapter.php#L33
https://github.com/silverstripe/silverstripe-s3/blob/pr/performance/src/Adapter/PublicCDNAdapter.php#L43

overall not sure the best way to handle this so you get the proper CDN URL

**Comment by obj63mc** [comment]
So we tested this out on another site as well yesterday afternoon that has about 10k image assets. All has been working fine and as expected. Would say this is good to go.

**Comment by wilr** [comment]
Merged now @obj63mc I'm happy it's a good initial step forward without making any major philosophical changes. 

Further work could be (I'm happy to hear people's thoughts as a trade off between 'correct' and 'fast')

`fileSize`, `mimeType`, `publicUrl` if not cached hits AWS to get that figured out.. 

Given that it probably doesn't change over time it could be saved to the db. That would cut down 3 queries per file on a cold cache.

**Pull request merged**
